name: masy
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  excel: ^2.0.4
  firebase_auth: ^4.3.0
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.15
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  flutter_zoom_drawer: ^3.0.4+1
  fluttericon: ^2.0.0
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  image_picker: ^0.8.6+4
  intl: ^0.17.0
  json_annotation: ^4.8.0
  open_file: ^3.2.1
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  readmore: ^2.2.0
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  syncfusion_flutter_datepicker: ^20.4.54

dev_dependencies:
  build_runner: ^2.3.3
  cloud_firestore_odm_generator: ^1.0.0-dev.45
  flutter_launcher_icons: ^0.12.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
